sudo: required 

language: python

python:
  - "3.6"      # current default Python on Travis CI
   
service:
 - docker


before_install:
 - docker build -t bert-ner:v1 -f ./Dockerfile.txt .

before_install: pip install docker-compose 

script:
 - docker run -p 5000:8000 bert-ner:v1 -- --coverage 