sudo: required 

language: python

python:
  - "3.6"      # current default Python on Travis CI
   
service:
 - docker

before_install:
 - pip install docker-compose
 - docker build -t ner-bert:v1 -f ./Dockerfile .

after_install:
  - docker images 

script:
 - docker run -d --name app  -p 80:80 ner-bert:v1 
 - docker ps -a
 - docker exec app python -m unittest discover

deploy:
 provider: elasticbeanstalk
 region: "ap-south-1"
 app: "bert-ner"
 env: "BertNer-env"
 bucket_name: "elasticbeanstalk-ap-south-1-238543985800"
 bucket_path: "bert-ner"
 on:
   branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
   secure: "$AWS_SECRET_KEY"
