sudo: required 

language: python

python:
  - "3.6"      # current default Python on Travis CI
   
service:
 - docker


before_install:
 - pip install docker-compose
 - docker build -t ner-bert:v1 -f ./Dockerfile.txt .

after_install:
  - docker images

script:
 - docker run -d --name app  -p 5000:8000 ner-bert:v1 
 - docker ps -a
 - docker exec app python -m unittest discover

after_script:
- docker rm -f app



