sudo: required 

language: python

python:
  - "3.6"      # current default Python on Travis CI
   
service:
 - docker


before_install:
 - docker build -t ner-bert:v1 -f ./Dockerfile.txt .

after_script:
  - docker images

script:
 - docker run -p 5000:8000 ner-bert:v1 

after_success:
 docker ps | grep -q ner-bert:v1


