name: deeplearningproject
channels:
- defaults
dependencies:
    - pytorch-pretrained-bert>=0.6.2
    - pytorch-transformers>=1.2.0
    - torch>=1.2.0
    - seqeval>=0.0.12
    - tqdm>=4.36.1
    - nltk>=3.4.5
    - Flask>=1.1.1
    - Flask-Cors>=3.0.8
    - Flask-Bootstrap>=3.3.7.1
    - Werkzeug>=0.16.0
    - pip:
        - pytorch-pretrained-bert>=0.6.2
        - pytorch-transformers>=1.2.0
        - torch>=1.2.0
        - seqeval>=0.0.12
        - tqdm>=4.36.1
        - nltk>=3.4.5
        - Flask>=1.1.1
        - Flask-Cors>=3.0.8
        - Flask-Bootstrap>=3.3.7.1
        - Werkzeug>=0.16.0